### ISSUE TITLE
MVP 

### ISSUE THREAD

**Issue by steveoni** [scatteredNote/scatteredNote#1]
Mvp workflow image
![123](https://user-images.githubusercontent.com/20904032/224537838-79600df3-a1db-488a-8dd8-3ed415d166c9.png)

## Acceptance
- [ ] We have a working demo containing the basic functionalities (create a note, index note, logged-in user, note display, and one of the extensions (browser or vscode or desktop app)

## Task

- [x] Create an example interface for the web --> this interface will later be recreated into a browser or vs code extension or desktop app #2 
- [x] Note publish workflow: `create note --> commit note  to github --> github action enables indexing to a search engine (Typsense for example) --> regenerate the static website on vercel`
- [x] investigate a proper way to index notes: should we go with typsense?
- [x] Create a simple interface to display notes containing search box, tags and notes
- [x] Enables login with github `octokit` https://www.npmjs.com/package/octokit gives us access to github functionalities both login, commit, and create actions
- [x] Research: research if its possible to create interface in vscode, chrome or we should go with desktop application
