### ISSUE TITLE
Make note public

### ISSUE THREAD

**Issue by steveoni** [scatteredNote/scatteredNote#10]
All users' notes are currently private to them. The initial design had a toggle button to control this per note. the core functionality to enable this is partially in the codebase. But need to think through how the UI will be displayed to users.

## Acceptance

- [ ] user can make note public or private
- [ ] user can see other users' notes per website and youtube  (with good UI display)

## Task

- [ ] Create a toggle button in editor page to toggle between public and private
- [ ] Provide UI for other user to easily see other users note per website and youtube
