### ISSUE TITLE
Grab-Note Interface

### ISSUE THREAD

**Issue by steveoni** [scatteredNote/scatteredNote#2]
![archivecreator](https://user-images.githubusercontent.com/20904032/224538857-ee3fd78e-fc93-45d9-b966-af9b3d03f903.png)

## Task

- [x] Grab display contains information copied from the web or vscode (can be text or image), but we are starting with text
- [x] Note editor is a rich type editor, accepts markdown
- [x] grab editor should also have code formatted - > if a javascript code is copied, user should be able to select the language and format the text e.g
This what was grabbed
```
const copied = "grabbed"
```
user specifies `js` hence it transforms it to:

```js
const copied = "grabbed"
```
- [x] new grabbed/note can either be a main topic, a sub-topic  or add to an existing note.. if it is a main topic or subtopic the note should have a title
- [x] grabbed/note should either be public or private
- [x] Tags should be created to allow grouping of topics and sub-topics
- [x] commit button should push to github and start all other workflow such as indexing and rebuilding static site

## package to consider
octokit https://www.npmjs.com/package/octokit
