### ISSUE TITLE
Chat with Note

### ISSUE THREAD

**Issue by steveoni** [scatteredNote/scatteredNote#6]
The main aim of the app is not just to curate information but to enable user chat with their note on any stored topic.

## Acceptance

- [ ] chat system is setup and the user can point to a topic and have a chat

## Task

- [ ] Research on the proper approach to get this done. we also want to include a reference (pointing to the note use for the response) to the ai language model result
- [ ] Generate task from the research

## Basic analysis

Packages to check for insight
* https://github.com/mayooear/gpt4-pdf-chatbot-langchain used langchain and I think this the UI https://ai-chatbot-starter.vercel.app/
* Get the idea about vercel ai SDK via https://github.com/vercel-labs/ai-chatbot
* https://github.com/bhaskatripathi/pdfGPT : made use of openai, universal sentence encoder and knn. this in python, we can convert to javascript, using scikit.js and tf.js
* notebook to learn how to use embedding from pinecone for chat: https://colab.research.google.com/github/pinecone-io/examples/blob/master/generation/langchain/handbook/08-langchain-retrieval-agent-fast.ipynb#scrollTo=pva9ehKXUpU2
and https://colab.research.google.com/github/pinecone-io/examples/blob/master/generation/generative-qa/openai/gen-qa-openai/gen-qa-openai-fast.ipynb
* understand vercel ai SDK and vector embedding with postgress using https://vercel.com/templates/next.js/nextjs-openai-doc-search-starter
