### ISSUE TITLE
Clean up codebase

### ISSUE THREAD

**Issue by steveoni** [scatteredNote/scatteredNote#9]
The codebase still contains some unused components and code. Also will be good to migrate the API code to make use of typescript, or rather convert the codebase to be fully typescript. Also, we have multiple state variables this can also be cleaned up

## Acceptance

- [ ] codebase looks good and cleaned up (no unused component, js to typescript, state well managed)

## Task 

- [ ] remove unused code and component
- [ ] convert to Typescript
- [ ] optimize state management
